// Mocks generated by Mockito 5.4.6 from annotations
// in merkledag/test/merkledag_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dart_cid/dart_cid.dart' as _i5;
import 'package:merkledag/src/broadcaster.dart' as _i6;
import 'package:merkledag/src/dag_syncer.dart' as _i2;
import 'package:merkledag/src/merkle_node.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DAGSyncer].
///
/// See the documentation for Mockito's code generation for more information.
class MockDAGSyncer<T> extends _i1.Mock implements _i2.DAGSyncer<T> {
  MockDAGSyncer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.MerkleNode<T>?> get(_i5.CID? cid) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [cid],
        ),
        returnValue: _i3.Future<_i4.MerkleNode<T>?>.value(),
      ) as _i3.Future<_i4.MerkleNode<T>?>);

  @override
  _i3.Future<void> put(_i4.MerkleNode<T>? node) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [node],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Broadcaster].
///
/// See the documentation for Mockito's code generation for more information.
class MockBroadcaster extends _i1.Mock implements _i6.Broadcaster {
  MockBroadcaster() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> broadcast(String? cidString) => (super.noSuchMethod(
        Invocation.method(
          #broadcast,
          [cidString],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<String> subscribe() => (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [],
        ),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);
}
