name: merkledag
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  dart_cid:
    path: /Users/stephanfeb/IdeaProjects/bsv_apps/dart-cid
  synchronized: ^3.3.0+3 # Using this for Lock

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
