name: merkledag
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  dart_cid:
    path: /Users/stephanfeb/IdeaProjects/bsv_apps/dart-cid
  synchronized: ^3.3.0+3 # Using this for Lock

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.10
  collection: ^1.19.0 # Already used in merkle_crdt.dart, ensure it's here for dev too
  logging: ^1.2.0 # Already used in merkle_crdt.dart
